name: deeptalk
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/fastai/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2023.08.22=h06a4308_0
  - libedit=3.1.20221030=h5eee18b_0
  - libffi=3.2.1=hf484d3e_1007
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=1.1.1w=h7f8727e_0
  - pip=23.3=py38h06a4308_0
  - python=3.8.0=h0371630_2
  - readline=7.0=h7b6447c_5
  - setuptools=68.0.0=py38h06a4308_0
  - sqlite=3.33.0=h62c20be_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.41.2=py38h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - aiohttp==3.9.0
      - aiosignal==1.3.1
      - anndata==0.9.2
      - annotated-types==0.6.0
      - anyio==4.0.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asciitree==0.3.3
      - asttokens==2.4.1
      - async-lru==2.0.4
      - async-timeout==4.0.3
      - attrs==23.1.0
      - babel==2.13.1
      - backcall==0.2.0
      - beautifulsoup4==4.12.2
      - bleach==6.1.0
      - build==1.0.3
      - certifi==2023.11.17
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cloudpickle==3.0.0
      - comm==0.2.0
      - contourpy==1.1.1
      - cryptography==41.0.5
      - cycler==0.12.1
      - dask==2023.5.0
      - dask-image==2023.3.0
      - debugpy==1.8.0
      - decorator==5.1.1
      - deeptalk-st==0.0.2
      - defusedxml==0.7.1
      - docrep==0.3.2
      - docutils==0.20.1
      - exceptiongroup==1.1.3
      - executing==2.0.1
      - fasteners==0.19
      - fastjsonschema==2.18.1
      - fonttools==4.44.3
      - fqdn==1.5.1
      - frozenlist==1.4.0
      - fsspec==2023.10.0
      - gensim==3.8.3
      - get-annotations==0.1.2
      - h5py==3.10.0
      - idna==3.4
      - igraph==0.10.8
      - imageio==2.33.0
      - importlib-metadata==6.8.0
      - importlib-resources==6.1.1
      - inflect==7.0.0
      - ipykernel==6.26.0
      - ipython==8.12.3
      - ipywidgets==8.1.1
      - isoduration==20.11.0
      - jaraco-classes==3.3.0
      - jedi==0.19.1
      - jeepney==0.8.0
      - jinja2==3.1.2
      - joblib==1.3.2
      - json5==0.9.14
      - jsonpointer==2.4
      - jsonschema==4.19.2
      - jsonschema-specifications==2023.7.1
      - jupyter==1.0.0
      - jupyter-client==8.6.0
      - jupyter-console==6.6.3
      - jupyter-core==5.5.0
      - jupyter-events==0.9.0
      - jupyter-lsp==2.2.0
      - jupyter-server==2.10.1
      - jupyter-server-terminals==0.4.4
      - jupyterlab==4.0.8
      - jupyterlab-pygments==0.2.2
      - jupyterlab-server==2.25.0
      - jupyterlab-widgets==3.0.9
      - keyring==24.3.0
      - kiwisolver==1.4.5
      - lazy-loader==0.3
      - leidenalg==0.10.1
      - llvmlite==0.38.1
      - locket==1.0.0
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - matplotlib==3.7.4
      - matplotlib-inline==0.1.6
      - matplotlib-scalebar==0.8.1
      - mdurl==0.1.2
      - mistune==3.0.2
      - more-itertools==10.1.0
      - multidict==6.0.4
      - natsort==8.4.0
      - nbclient==0.9.0
      - nbconvert==7.11.0
      - nbformat==5.9.2
      - nest-asyncio==1.5.8
      - networkx==3.1
      - nh3==0.2.14
      - notebook==7.0.6
      - notebook-shim==0.2.3
      - numba==0.55.2
      - numcodecs==0.12.1
      - numpy==1.22.4
      - omnipath==1.0.7
      - orderedset==2.0.3
      - overrides==7.4.0
      - packaging==23.2
      - pandas==2.0.3
      - pandocfilters==1.5.0
      - parso==0.8.3
      - partd==1.4.1
      - patsy==0.5.3
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==10.1.0
      - pims==0.6.1
      - pkginfo==1.9.6
      - pkgutil-resolve-name==1.3.10
      - platformdirs==3.11.0
      - prometheus-client==0.18.0
      - prompt-toolkit==3.0.39
      - psutil==5.9.6
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pycparser==2.21
      - pydantic==2.5.1
      - pydantic-core==2.14.3
      - pygments==2.17.1
      - pynndescent==0.5.10
      - pyparsing==3.1.1
      - pyproject-hooks==1.0.0
      - python-dateutil==2.8.2
      - python-json-logger==2.0.7
      - pytz==2023.3.post1
      - pywavelets==1.4.1
      - pyyaml==6.0.1
      - pyzmq==25.1.1
      - qtconsole==5.5.1
      - qtpy==2.4.1
      - readme-renderer==42.0
      - referencing==0.30.2
      - requests==2.31.0
      - requests-toolbelt==1.0.0
      - rfc3339-validator==0.1.4
      - rfc3986==2.0.0
      - rfc3986-validator==0.1.1
      - rich==13.7.0
      - rpds-py==0.12.0
      - scanpy==1.9.6
      - scikit-image==0.21.0
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - seaborn==0.12.2
      - secretstorage==3.3.3
      - send2trash==1.8.2
      - session-info==1.0.0
      - six==1.16.0
      - slicerator==1.1.0
      - smart-open==6.4.0
      - sniffio==1.3.0
      - soupsieve==2.5
      - squidpy==1.2.3
      - stack-data==0.6.3
      - statsmodels==0.14.0
      - stdlib-list==0.10.0
      - terminado==0.17.1
      - texttable==1.7.0
      - threadpoolctl==3.2.0
      - tifffile==2023.7.10
      - tinycss2==1.2.1
      - tomli==2.0.1
      - toolz==0.12.0
      - torch==1.8.1+cu111
      - torch-cluster==1.5.9
      - torch-scatter==2.0.7
      - torch-sparse==0.6.10
      - torch-spline-conv==1.2.1
      - torchaudio==0.8.1
      - torchvision==0.9.1+cu111
      - tornado==6.3.3
      - tqdm==4.66.1
      - traitlets==5.13.0
      - twine==4.0.2
      - types-python-dateutil==2.8.19.14
      - typing-extensions==4.8.0
      - tzdata==2023.3
      - umap-learn==0.5.5
      - uri-template==1.3.0
      - urllib3==2.1.0
      - validators==0.22.0
      - wcwidth==0.2.9
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.6.4
      - widgetsnbextension==4.0.9
      - wrapt==1.16.0
      - xarray==2023.1.0
      - yarl==1.9.2
      - zarr==2.16.1
      - zipp==3.17.0
prefix: /mnt/test/a3/anaconda3/envs/testpypi
